In [213]:
import pandas as pd
import numpy as np
from random import randint

In [214]:
dataset = pd.read_csv('dataset_dbscan.csv', delimiter=';')

In [215]:
array_dataset = dataset.drop('No',axis=1)
array_dataset = array_dataset.values
array_dataset

array([[85, 85,  0],
       [80, 90,  0],
       [65, 70,  0],
       [72, 95,  0],
       [83, 78,  0],
       [60, 75,  0],
       [78, 85,  0],
       [64, 65,  0],
       [69, 70,  0],
       [75, 88,  0]], dtype=int64)

## Calculate Distance

In [216]:
def cal_distance(data1, data2):
    temp1 = data1[0]
    temp2 = data2[0]
    humd1 = data1[1]
    humd2 = data2[1]
    distance = abs(temp1-temp2)+abs(humd1-humd2)
    return distance

In [217]:
cal_distance(array_dataset[1],array_dataset[2])

35

## Define Neighbors & Cluster

In [218]:
def get_neighbors(dataset,cp):
    #random_index = randint(0,len(dataset))
    distance_neighbors = []
    index_neighbors = []
    neighbors = []
    central_point = cp
    eps = 15
    
    for i in range(len(dataset)):
        count_distance = cal_distance(central_point,dataset[i])
        if count_distance <= eps and count_distance!=0:
            #distance_neighbours.append(count_distance)
            index_neighbors.append(i)
            
    #neighbours = dict(zip(index_neighbours,distance_neighbours))
    return index_neighbors

def define_cluster(dataset,neighbor_array,cluster,minPts):
    
    #X: Semua point yg ada pada dataset
    #NeighborsPts : semua index yg merupakan ketetanggaan hasil dari perhitungan minskowski
    #C : Label untuk cluster baru 
    count=0
    while count <len(neighbor_array):
        next_point=neighbor_array[count]
        print('central point :',next_point)
        if dataset[next_point,-1]==-1:
            dataset[next_point,-1]=cluster
            
        elif dataset[next_point,-1]==0:
            dataset[next_point,-1]=cluster
        
            next_point_neighbor=get_neighbors(dataset[:,:-1],dataset[next_point,:-1])
            
            if len(next_point_neighbor)>=minPts:
                
                print("neigbor dari data",next_point,":", next_point_neighbor)
                neighbor_array = np.unique(np.concatenate((neighbor_array,next_point_neighbor)))
                print("all neighbor :",neighbor_array,"\n")
                print(dataset,"\n")
        else:
            print("sudah memiliki cluster\n")
        count+=1
    print("Hasil Clustering",cluster,"\n",dataset,'\n\n============================================================\n')
        
def main_dbscan(dataset,minPts):
    cluster = 0
    central_point = 2
    
    for i in range(central_point,len(dataset)):
        if (dataset[i,-1]!=0):
            continue
        
        neighbor_array=get_neighbors(dataset[:,:-1],dataset[i,:-1])
        print("central point :",i)
        print("neighbor dari data",i,":",neighbor_array)
        if len(neighbor_array)<minPts:
            dataset[i,-1]=-1
            print(dataset,'\ndata noise\n')
        else :
            cluster+=1
            dataset[i,-1] = cluster
            #print("central point :",i)
            print(dataset,'\n')
            define_cluster(dataset,neighbor_array,cluster,minPts)
        
    return dataset

In [219]:
array_dataset = main_dbscan(array_dataset,3)

central point : 2
neighbor dari data 2 : [5, 7, 8]
[[85 85  0]
 [80 90  0]
 [65 70  1]
 [72 95  0]
 [83 78  0]
 [60 75  0]
 [78 85  0]
 [64 65  0]
 [69 70  0]
 [75 88  0]] 

central point : 5
neigbor dari data 5 : [2, 7, 8]
all neighbor : [2 5 7 8] 

[[85 85  0]
 [80 90  0]
 [65 70  1]
 [72 95  0]
 [83 78  0]
 [60 75  1]
 [78 85  0]
 [64 65  0]
 [69 70  0]
 [75 88  0]] 

central point : 5
sudah memiliki cluster

central point : 7
neigbor dari data 7 : [2, 5, 8]
all neighbor : [2 5 7 8] 

[[85 85  0]
 [80 90  0]
 [65 70  1]
 [72 95  0]
 [83 78  0]
 [60 75  1]
 [78 85  0]
 [64 65  1]
 [69 70  0]
 [75 88  0]] 

central point : 8
neigbor dari data 8 : [2, 5, 7]
all neighbor : [2 5 7 8] 

[[85 85  0]
 [80 90  0]
 [65 70  1]
 [72 95  0]
 [83 78  0]
 [60 75  1]
 [78 85  0]
 [64 65  1]
 [69 70  1]
 [75 88  0]] 

Hasil Clustering 1 
 [[85 85  0]
 [80 90  0]
 [65 70  1]
 [72 95  0]
 [83 78  0]
 [60 75  1]
 [78 85  0]
 [64 65  1]
 [69 70  1]
 [75 88  0]] 


central point : 3
neighbor dari data 3 

In [220]:
array_dataset

array([[85, 85,  2],
       [80, 90,  2],
       [65, 70,  1],
       [72, 95,  2],
       [83, 78,  2],
       [60, 75,  1],
       [78, 85,  2],
       [64, 65,  1],
       [69, 70,  1],
       [75, 88,  2]], dtype=int64)